name: docx_mailmerge
description: Perform a mail merge operation on DOCX files
version: 1.0.0
repository: https://github.com/Wetbikeboy2500/docx_mailmerge

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  archive: ^3.1.6
  xml: ^5.3.1
  commandline_splitter2: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
