name: docx_mailmerge
description: Package for performing a mailmerge operation on merge fields within a DOCX document
version: 1.0.3
repository: https://github.com/Wetbikeboy2500/docx_mailmerge

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  archive: ^3.1.6
  xml: '>=5.3.1 <7.0.0'
  shlex: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
