name: docx_mailmerge
description: Package for performing a mailmerge operation on merge fields within a DOCX document
version: 2.0.0
repository: https://github.com/Wetbikeboy2500/docx_mailmerge

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  archive: ^3.1.6
  xml: '^6.0.0'
  shlex: ^2.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
